# Real estate prices tracker

## EDA

### reading the dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
pwd()

'd:\\Projects\\real estate analysis\\scripts'

In [3]:
data = pd.read_csv(r"D:\Projects\real estate analysis\data\csv\magicbricks_mumbai_20260814_161732.csv")
data.head()

,OwnershipTypeD,ac,acD,achTdS,achTm,achTmS,actualOwner,ad_text,adroomD,agtCerStatus,...,tmsrt,transType,transactionTypeD,ty,ubicnt,url,userType,wapImgUrl,wapImgUrl1,waterStatus
0,NaN,11654.0,10 to 15 years,0,0,0,17800235,Sale Individual Mumbai Maharashtra India vir...,NaN,NaN,...,232027,Sale,Resale,10002,50,1-BHK-310-Sq-ft-Multistorey-Apartment-FOR-Sale...,Owner,https://img.staticmb.com/mbphoto/property/crop...,https://img.staticmb.com/mbphoto/property/crop...,NaN
1,NaN,11655.0,15 to 20 years,0,0,0,58928717,Sale Individual Mumbai Maharashtra India 100...,NaN,NaN,...,93000,Sale,Resale,10002,50,1-BHK-440-Sq-ft-Multistorey-Apartment-FOR-Sale...,Owner,https://img.staticmb.com/mbphoto/property/crop...,https://img.staticmb.com/mbphoto/property/crop...,NaN
2,Co-operative Society,11654.0,10 to 15 years,0,0,0,49937177,Sale Individual Mumbai Maharashtra India Sid...,NaN,N,...,52535,Sale,Resale,10003,50,1-BHK-365-Sq-ft-Builder-Floor-Apartment-FOR-Sa...,Owner,https://img.staticmb.com/mbphoto/property/crop...,https://img.staticmb.com/mbphoto/property/crop...,Water Availability 24 Hours Available
3,Co-operative Society,11654.0,10 to 15 years,0,0,0,66070239,Sale Individual Mumbai Maharashtra India 404...,NaN,NaN,...,223334,Sale,Resale,10002,50,1-BHK-525-Sq-ft-Multistorey-Apartment-FOR-Sale...,Owner,https://img.staticmb.com/mbphoto/property/crop...,https://img.staticmb.com/mbphoto/property/crop...,Water Availability 24 Hours Available
4,NaN,NaN,NaN,0,0,0,34200887,Sale Individual Mumbai Maharashtra India Bal...,NaN,NaN,...,220815,Sale,Resale,10003,50,1-BHK-500-Sq-ft-Builder-Floor-Apartment-FOR-Sa...,Owner,https://img.staticmb.com/mbphoto/property/crop...,https://img.staticmb.com/mbphoto/property/crop...,NaN

In [4]:
# print(f"no. of rows, cols : {data.shape}\n")
print(f"info : {data.info()}\n")
# print(f"desc : {data.describe()}\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Columns: 225 entries, OwnershipTypeD to waterStatus
dtypes: bool(6), float64(45), int64(50), object(124)
memory usage: 51.6+ KB
info : None

In [ ]:
# columns

colnames = data.columns
for i in colnames:
    print(i)

### selecting only needed cols

In [6]:
with open('colnames.txt','w') as file:
    for item in colnames:
        file.write(f"{item}\n")

In [7]:
with open("neededcols.txt", "r") as file:
    items = file.read().split(",")

In [ ]:
items

In [9]:
cols_to_keep = items
existing_cols = [col for col in cols_to_keep if col in data.columns] 
data_needed_cols = data[existing_cols]

In [10]:
data_needed_cols.head(1)

,acD,price,priceD,sqFtPrice,minPrice,maxPrice,bedroomD,bathD,balconiesD,carpetArea,...,endDateT,endDt,cowDays,dsla,nriPref,tenantsPreference,propertyTitle,adroomD,caSqFt,lmtDName
0,10 to 15 years,1200000,12 Lac,3871.0,1090000,1200000,1,1,NaN,270.0,...,2026-12-25T18:14:57.000Z,"Dec 25, '26",0,2.0,NaN,Bachelors/Family,1BHK Multistorey Apartment for Resale in Anand...,NaN,310.0,Dadar West

In [11]:
data_needed_cols.to_csv(
    "data-with-neededcols.csv")

### Now we choose the columns we are gonna work with

In [12]:
imp_cols = ['acD','price','sqFtPrice','bedroomD','bathD','balconiesD','carpetArea','coveredArea','floorNo','floors','furnishedD','facingD','amenFacingD','propTypeD','transactionTypeD','possStatusD','ecd','ctName','locSeoName','prjname','landmark','lmtDName','ltcoordGeo','luxAmenitiesD','parkingD','waterStatus','powerStatusD','maintenanceCharges','maintenanceD','flooringTyD','reraValidity','OwnershipTypeD','tenantsPreference','postDateT','propertyTitle','adroomD']

In [14]:
working_dataset = data_needed_cols[imp_cols]
working_dataset.head(2)

,acD,price,sqFtPrice,bedroomD,bathD,balconiesD,carpetArea,coveredArea,floorNo,floors,...,powerStatusD,maintenanceCharges,maintenanceD,flooringTyD,reraValidity,OwnershipTypeD,tenantsPreference,postDateT,propertyTitle,adroomD
0,10 to 15 years,1200000,3871.0,1,1,NaN,270.0,310.0,1,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Bachelors/Family,2026-08-12T18:14:57.000Z,1BHK Multistorey Apartment for Resale in Anand...,NaN
1,15 to 20 years,2000000,4545.0,1,1,NaN,317.0,440.0,Ground,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Bachelors/Family,2026-08-12T16:51:50.000Z,1BHK Multistorey Apartment for Resale in Ganga...,NaN

In [ ]:
print(working_dataset[['carpetArea','price']])